services:
  postgres:
    extends:
      file: docker-compose.dbs.yml
      service: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    extends:
      file: docker-compose.dbs.yml
      service: redis
    ports:
      - 6379:6379

  elasticsearch:
    extends:
      file: docker-compose.dbs.yml
      service: elasticsearch
    ports:
      - 9200:9200
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  mongodb:
    extends:
      file: docker-compose.dbs.yml
      service: mongodb
    volumes:
      - mongo:/data/db
    ports:
      - 27017:27017

  nginx:
    image: nginx:1.19.6
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    network_mode: $NGINX_NETWORK_MODE
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    environment:
      API_HOST: $API_HOST
      API_PORT: $API_PORT
      NOTIFIER_HOST: $NOTIFIER_HOST
      UI_HOST: $UI_HOST
      DEVELOPERS_HOST: $DEVELOPERS_HOST
      NGINX_PROXY_HOST: $NGINX_PROXY_HOST
      ELASTIC_SEARCH_HOST: $ELASTIC_SEARCH_HOST
      STORYBOOK_HOST: $STORYBOOK_HOST
    ports:
      - "80:80"

volumes:
  postgres:
  elasticsearch:
  mongo:
