apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - backend-configmap.yaml
  - backend-resourcequota.yaml
  - backend-limitrange.yaml
  - backend-secretstore.yaml
  - backend-externalsecret.yaml

# Common labels
labels:
  - pairs:
      app.kubernetes.io/part-of: trackdechets
      app.kubernetes.io/managed-by: kustomize
