apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - backend-configmap.yaml
  - backend-resourcequota.yaml
  - backend-limitrange.yaml
  - ../external-secrets/backend-secretstore.yaml
  - ../external-secrets/backend-externalsecret.yaml
  - ../databases/postgresql.yaml
  - ../databases/redis.yaml
  - ../databases/elasticsearch.yaml
  - ../databases/mongodb.yaml
  - ../apps/api.yaml
  - ../apps/notifier.yaml
  - ../apps/cron.yaml
  - ../apps/queue-workers.yaml
  - ../apps/prisma-migrate-job.yaml

# Common labels
commonLabels:
  app.kubernetes.io/part-of: trackdechets
  app.kubernetes.io/managed-by: kustomize

# Note: Resources are in trackdechets-backend namespace
