apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - resourcequota.yaml
  - limitrange.yaml
  - ../databases/postgresql.yaml
  - ../databases/redis.yaml
  - ../databases/elasticsearch.yaml
  - ../databases/mongodb.yaml
  - ../apps/ui.yaml
  - ../apps/api.yaml
  - ../apps/notifier.yaml
  - ../apps/cron.yaml
  - ../apps/queue-workers.yaml
  - ../ingress/ingress.yaml

# Common labels applied to all resources
commonLabels:
  app.kubernetes.io/part-of: trackdechets
  app.kubernetes.io/managed-by: kustomize

# Namespace for all resources
namespace: trackdechets
