apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - configmap.yaml
  - secrets.yaml
  - resourcequota.yaml
  - limitrange.yaml

# Common labels applied to all resources
labels:
  - pairs:
      app.kubernetes.io/part-of: trackdechets
      app.kubernetes.io/managed-by: kustomize
