apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - frontend-configmap.yaml
  - frontend-resourcequota.yaml
  - frontend-limitrange.yaml
  - frontend-secretstore.yaml
  - frontend-externalsecret.yaml

# Common labels
labels:
  - pairs:
      app.kubernetes.io/part-of: trackdechets
      app.kubernetes.io/managed-by: kustomize
