---
apiVersion: v1
kind: Namespace
metadata:
  name: trackdechets-frontend
  labels:
    name: trackdechets-frontend
    app.kubernetes.io/part-of: trackdechets
    app.kubernetes.io/component: frontend