name: Build & Test

on: pull_request

jobs:
  front:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: back/package-lock.json

      - name: Install dependencies
        run: npm ci
      - name: Generate files
        run: npm run generate
      - name: Run linter
        run: npm run lint
      - name: Run typecheck
        run: npm run types
      - name: Run tests
        run: npm test

  back:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: back/package-lock.json

      - name: Install dependencies
        run: npm ci
      - name: Generate files
        run: npm run generate
      - name: Run linter
        run: npm run lint
      - name: Run typecheck
        run: npm run types
      - name: Check migrations
        run: npm run check:migrations
      - name: Run tests
        run: npm test -- --forceExit
        env:
          EMAIL_BACKEND: "console"
          SIB_BASE_URL: "http://mailservice"
          MAIN_TEMPLATE_ID: "9"
          SECURITY_CODE_RENEWAL_TEMPLATE_ID: "6"
          FIRST_ONBOARDING_TEMPLATE_ID: "246"
          PRODUCER_SECOND_ONBOARDING_TEMPLATE_ID: "248"
          PROFESIONAL_SECOND_ONBOARDING_TEMPLATE_ID: "250"
          VERIFIED_FOREIGN_TRANSPORTER_COMPANY_TEMPLATE_ID: "247"
          DATABASE_URL: "postgresql://user:password@postgres:5432/db"
          TD_COMPANY_ELASTICSEARCH_INDEX: "stocketablissement-production"
          TD_COMPANY_ELASTICSEARCH_URL: ${{ secrets.TD_COMPANY_ELASTICSEARCH_URL }}
          TD_COMPANY_ELASTICSEARCH_CACERT: ${{ secrets.TD_COMPANY_ELASTICSEARCH_CACERT }}

  doc:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: doc
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: doc/yarn.lock

      - run: yarn install --frozen-lockfile
      - name: Test Build
        run: yarn build
