

# Workflow de déploiement
# Le front et le back ne sont pas inclut dans ce fichier car leur déploiement
# se fait automatiquement via l'intégration Scalingo <> Github
name: Deploy Docs and Sentry Release on production

on:
  push:
    branches:
      - master

jobs:
  sentry-release-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run npm ci
        run: npm ci

      - name: Run build
        run: npx nx run-many -t build

      - name: Create a Sentry Release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: betagouv
          SENTRY_URL: https://sentry.incubateur.net/
        with:
          environment: production
          sourcemaps: ./dist/apps/api ./dist/front/assets
          projects: trackdechets-api trackdechets-front
          ignore_missing: true

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - run: npm ci
      - name: Build
        run: npx nx run doc:build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/apps/doc
