# Workflow de déploiement
# Le front et le back ne sont pas inclut dans ce fichier car leur déploiement
# se fait automatiquement via l'intégration Scalingo <> Github
name: Deploy Sentry Release on recette

on: pull_request

jobs:
  sentry-release-recette:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: Run npm ci
        run: npm ci
      - name: Run authorized scripts
        run: npx allow-scripts

      - name: Run build
        run: npx nx run-many -t build

      - name: Create a Sentry Release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN_TD }}
          SENTRY_ORG: betagouv
          SENTRY_URL: https://sentry.incubateur.net/
          SENTRY_LOG_LEVEL: debug
        with:
          environment: recette
          sourcemaps: ./dist/apps/api ./dist/front/assets
          projects: trackdechets-api trackdechets-front
          ignore_missing: true
